version: '3.8'

services:
  interview-production-green:
    container_name: interview-production-green
    image: syh24/interview
    ports:
      - "8081:8080"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
    volumes:
      - logs:/log
    networks:
      - interview-production_default

  interview-production-blue:
    container_name: interview-production-blue
    image: syh24/interview
    ports:
      - "8080:8080"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
    volumes:
      - logs:/log
    networks:
      - interview-production_default


  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - interview-production_default

networks:
  interview-production_default:
    external: true

volumes:
  logs:
    name: logs
    driver: local
    driver_opts:
      type: none
      device: /home/ubuntu/logs
      o: bind